### ISSUE TITLE
setting basedir as absolute can cause deployment issues

### ISSUE THREAD

**Issue by corsen2000** [vuejs/vue-ssr-webpack-plugin#3]
As of `1.0.2` `basedir` is now being set. It is being set to `compiler.options.output.path` which must be an absolute path per webpack.

This breaks my deployment system. The deployment system runs the build in a `/tmp` folder and then copies the project for hosting. At build time `basedir` is getting hard coded to an absolute path in the `/tmp` location.

The [server-renderer allows basedir to be overriden](https://github.com/vuejs/vue/tree/dev/packages/vue-server-renderer#basedir), so that can be used as a fix. I'm using Nuxt.js where I don't have access to this option though. I've already [opened an issue there](https://github.com/nuxt/nuxt.js/issues/462) to consider a fix from that side.

I am working around this with a subsequent build process that removes `basedir`. The default behavior in `server-renderer` should `basedir` not be specified seems to work for me.

I don't know why this change was done, but if there is a way to do it that does not specify `basedir` as an absolute path it may make it easier to use this project without additional configuration elsewhere.

Thank you.

**Comment by yyx990803** [comment]
This was added to ensure externalized modules can work properly `vue-server-renderer` is linked / not placed in the same file tree with those dependencies.

I think we will probably remove the build-time hard coded basedir in this plugin here.

**Comment by yyx990803** [comment]
1.0.3 no longer hard codes the build time basedir.
