### ISSUE TITLE
Can not import node_modules css

### ISSUE THREAD

**Issue by Val-istar-Guo** [vuejs/vue-ssr-webpack-plugin#6]
my webpack config

![image](https://cloud.githubusercontent.com/assets/12405937/25301095/35d9eab8-2751-11e7-8b10-e172a2b6fb89.png)

 js file

![image](https://cloud.githubusercontent.com/assets/12405937/25301097/525b60d6-2751-11e7-93c3-19b61aac9049.png)

when i use `import '../node_modules/normalize.css/normalize.css';`
everythings will be ok.

however when i use `import 'normalize.css';`

webpack packing pass but i visit `128.0.0.1:8080` vue ssr throw error:

![image](https://cloud.githubusercontent.com/assets/12405937/25301137/cb5a6dec-2751-11e7-8816-5b9060a430dc.png)

project url: https://github.com/Val-istar-Guo/ab_test_config_server/commit/aa697f48ba576b34f186854aa8f108bf28ea3342

**Comment by yyx990803** [comment]
Exclude that dependency from your server-side webpack config's `externals`.

**Comment by Val-istar-Guo** [comment]
thanks...

**Comment by Val-istar-Guo** [comment]
😂 I am stupid
