### ISSUE TITLE
support setting output filename according to different entries

### ISSUE THREAD

**Issue by mapleeit** [vuejs/vue-ssr-webpack-plugin#9]
In multi entries circumstances, can't set different server-bundle-json name.

Example: 
```
{
    // 将 entry 指向应用程序的 server entry 文件
    entry: {
        share: '../modules/share/src/entry-server.js',
        share_copy: '../modules/share_copy/src/entry-server.js',
    },
    output: {
        path: 'path/to/dist',
        filename: '[name].js',
        libraryTarget: 'commonjs2'
    },
    plugins: [
        new VueSSRServerPlugin()
    ]
})
```

I found that in this multi entries, it will not generate one bigger `vue-ssr-server-bundle.json` file instead of two `vue-ssr-server-bundle.json`. Is this a bug?

**Comment by yyx990803** [comment]
This plugin has been deprecated. Use `vue-server-renderer/server-plugin` instead. See http://ssr.vuejs.org/en/api.html#webpack-plugins
